/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormContainer: typeof import('./../src/components/form-container.vue')['default']
    Fullscreen: typeof import('./../src/layouts/view/header-right/fullscreen.vue')['default']
    FullScreen: typeof import('./../src/layouts/view/header-right/full-screen.vue')['default']
    IframeLayout: typeof import('./../src/layouts/iframe/iframe-layout.vue')['default']
    IMaterialSymbolsFullscreenExit: typeof import('@vexip-ui/icons')['MaterialSymbolsFullscreenExit']
    IXmark: typeof import('@vexip-ui/icons')['Xmark']
    ListContainer: typeof import('./../src/components/list-container.vue')['default']
    Message: typeof import('./../src/layouts/view/header-right/message.vue')['default']
    RichEditor: typeof import('./../src/components/rich-editor.vue')['default']
    RightMessage: typeof import('./../src/layouts/view/header-right/right-message.vue')['default']
    RightSearch: typeof import('./../src/layouts/view/header-right/right-search.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Svg: typeof import('./../src/components/svg.vue')['default']
    ThemeSwitch: typeof import('./../src/layouts/view/header-right/theme-switch.vue')['default']
    VBreadcrumb: typeof import('vexip-ui')['Breadcrumb']
    VButton: typeof import('vexip-ui')['Button']
    VCard: typeof import('vexip-ui')['Card']
    VColumn: typeof import('vexip-ui')['Column']
    VConfigProvider: typeof import('vexip-ui')['ConfigProvider']
    VContextmenu: typeof import('vexip-ui')['Contextmenu']
    VDatePicker: typeof import('vexip-ui')['DatePicker']
    VDropdown: typeof import('vexip-ui')['Dropdown']
    VForm: typeof import('vexip-ui')['Form']
    VFormItem: typeof import('vexip-ui')['FormItem']
    VFormSubmit: typeof import('vexip-ui')['FormSubmit']
    VFullScreen: typeof import('vexip-ui')['FullScreen']
    VH4: typeof import('vexip-ui')['H4']
    VIcon: typeof import('vexip-ui')['Icon']
    ViewLayout: typeof import('./../src/layouts/view/view-layout.vue')['default']
    VInput: typeof import('vexip-ui')['Input']
    VLayout: typeof import('vexip-ui')['Layout']
    VLinker: typeof import('vexip-ui')['Linker']
    VNativeScroll: typeof import('vexip-ui')['NativeScroll']
    VPagination: typeof import('vexip-ui')['Pagination']
    VResizeObserver: typeof import('vexip-ui')['ResizeObserver']
    VRow: typeof import('vexip-ui')['Row']
    VSpace: typeof import('vexip-ui')['Space']
    VSwitch: typeof import('vexip-ui')['Switch']
    VTable: typeof import('vexip-ui')['Table']
    VTableColumn: typeof import('vexip-ui')['TableColumn']
    VTabNav: typeof import('vexip-ui')['TabNav']
    VTabNavItem: typeof import('vexip-ui')['TabNavItem']
    VTextarea: typeof import('vexip-ui')['Textarea']
    VTooltip: typeof import('vexip-ui')['Tooltip']
    VUpload: typeof import('vexip-ui')['Upload']
  }
}
