/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormContainer: typeof import('./../src/components/form-container.vue')['default']
    IframeLayout: typeof import('./../src/layouts/iframe/iframe-layout.vue')['default']
    ListContainer: typeof import('./../src/components/list-container.vue')['default']
    RichEditor: typeof import('./../src/components/rich-editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Svg: typeof import('./../src/components/svg.vue')['default']
    VButton: typeof import('vexip-ui')['Button']
    VCard: typeof import('vexip-ui')['Card']
    VConfigProvider: typeof import('vexip-ui')['ConfigProvider']
    VDivider: typeof import('vexip-ui')['Divider']
    VForm: typeof import('vexip-ui')['Form']
    VFormItem: typeof import('vexip-ui')['FormItem']
    VFormSubmit: typeof import('vexip-ui')['FormSubmit']
    VH1: typeof import('vexip-ui')['H1']
    ViewLayout: typeof import('./../src/layouts/view/view-layout.vue')['default']
    VInput: typeof import('vexip-ui')['Input']
    VLinker: typeof import('vexip-ui')['Linker']
    VRow: typeof import('vexip-ui')['Row']
  }
}
